service: createCatalog
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    EJECUTEQUERIES: arn:aws:lambda:us-east-1:831011833915:function:ejecuteQueries-dev-ejecuteQueries

plugins:
  - serverless-plugin-include-dependencies
  - serverless-python-requirements

functions:
  createCatalog:
    handler: handler.createCatalog
    events:
      - http:
          path: createCatalog
          method: post
          cors: true
